server:
  port: 8095
spring:
  application:
    name: rocketmq
myhost: 127.0.0.1
rocketmq:
  ###consumer
  consumer:
    consumeMessageBatchMaxSize: 1
    consumeThreadMax: 64
    consumeThreadMin: 20
    groupName: ${spring.application.name}
    ##该应用是否启用消费者
    isOnOff: 'on'
    #mq的nameserver地址
    namesrvAddr: ${myhost}:9876
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: rocketCommonTopic

  ###producer
  producer:
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: ${spring.application.name}
    #该应用是否启用生产者
    isOnOff: 'on'
    #消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    #mq的nameserver地址
    namesrvAddr: ${myhost}:9876
    #发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    #发送消息超时时间,默认3000
    sendMsgTimeout: 3000

